package Telas;



import DAO.CandidatoDAO;
import DAO.EleitorDAO;
import Global.VariavelGlobal;
import classesModelo.Candidato;
import classesModelo.Eleitor;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Luciana
 */
public class Apuracao extends javax.swing.JFrame {

    /**
     * Creates new form Apuracao
     */
    public Apuracao() {
        initComponents();
    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTapuracao = new javax.swing.JTable();
        jBgerarApuracao = new javax.swing.JButton();
        jBencerrarSecao = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("APURAÇÃO");
        setMinimumSize(new java.awt.Dimension(900, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("APURAÇÃO DOS VOTOS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, 300, -1));

        jTapuracao.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTapuracao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NÚMERO", "NOME", "VICE", "PARTIDO", "VOTOS"
            }
        ));
        jTapuracao.setRowHeight(24);
        jScrollPane1.setViewportView(jTapuracao);
        if (jTapuracao.getColumnModel().getColumnCount() > 0) {
            jTapuracao.getColumnModel().getColumn(0).setMaxWidth(70);
            jTapuracao.getColumnModel().getColumn(3).setMaxWidth(70);
            jTapuracao.getColumnModel().getColumn(4).setMaxWidth(120);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 850, 210));

        jBgerarApuracao.setBackground(new java.awt.Color(0, 153, 153));
        jBgerarApuracao.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBgerarApuracao.setText("GERAR APURAÇÃO");
        jBgerarApuracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBgerarApuracaoActionPerformed(evt);
            }
        });
        getContentPane().add(jBgerarApuracao, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 200, 50));

        jBencerrarSecao.setBackground(new java.awt.Color(255, 51, 51));
        jBencerrarSecao.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBencerrarSecao.setText("ENCERRAR SEÇÃO");
        jBencerrarSecao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBencerrarSecaoActionPerformed(evt);
            }
        });
        getContentPane().add(jBencerrarSecao, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 410, 170, 40));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBgerarApuracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBgerarApuracaoActionPerformed
        List <Candidato> listaCandidato;
        
        CandidatoDAO dao;
        dao = new CandidatoDAO();
        
        Candidato can;
        
        listaCandidato = dao.listarCandidatos();
           
        DefaultTableModel model = (DefaultTableModel) jTapuracao.getModel();
        model.setNumRows(0);
        
        for (int y = 0; y < listaCandidato.size(); y++) {
            can = listaCandidato.get(y);
            //JOptionPane.showMessageDialog(null, y + " - " + alu.getNome());
           model.addRow(new Object[] {can.getNumero(),can.getNome(), can.getVice(),
           can.getPartido(),can.getVotos()});
                                       
        }    
    }//GEN-LAST:event_jBgerarApuracaoActionPerformed

    private void jBencerrarSecaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBencerrarSecaoActionPerformed
       int i = JOptionPane.showConfirmDialog(
        null, 
        "Tem certeza que deseja encerrar seção,está ação limpará todos os votos"
        );
        if(i == JOptionPane.YES_OPTION) {
        System.out.println("Clicou em Sim");
        
        Candidato can;
        can = new Candidato();
               
        
        CandidatoDAO bdc;
        bdc = new CandidatoDAO();
        
        
        bdc.zerarVotos(can);
             
        
        
        Eleitor ele;
        ele = new Eleitor();
        
        ele.setTitulo(VariavelGlobal.tituloEleitor);
         
        EleitorDAO bde;
        bde = new EleitorDAO();
        
        
        bde.zerarVotoEleitor(ele);
        
         TelaAbrir fabrir;
         fabrir = new TelaAbrir();
         fabrir.setVisible(true);
         
         dispose();
        }
        else if(i == JOptionPane.NO_OPTION) {
        System.out.println("Clicou em Não");
        }
        else if(i == JOptionPane.CANCEL_OPTION) {
        System.out.println("Clicou em Cancel");
        }
    }//GEN-LAST:event_jBencerrarSecaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Apuracao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Apuracao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Apuracao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Apuracao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Apuracao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBencerrarSecao;
    private javax.swing.JButton jBgerarApuracao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTapuracao;
    // End of variables declaration//GEN-END:variables
}
