/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import javax.swing.JOptionPane;

/**
 *
 * @author Luciana
 */
public class ConfirmarEncerramento extends javax.swing.JFrame {

    /**
     * Creates new form ConfirmarEncerramento
     */
    public ConfirmarEncerramento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPFconfirmarFim = new javax.swing.JPasswordField();
        jBencerrar = new javax.swing.JButton();
        jBvoltarParaEleitor = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ENCERRAR");
        setMinimumSize(new java.awt.Dimension(700, 450));
        setPreferredSize(new java.awt.Dimension(700, 450));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("ENCERRAR VOTAÇÃO");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Insira a senha");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, -1, -1));

        jPFconfirmarFim.setText("jPasswordField1");
        getContentPane().add(jPFconfirmarFim, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, 190, 40));

        jBencerrar.setBackground(new java.awt.Color(0, 153, 153));
        jBencerrar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBencerrar.setText("ENCERRAR");
        jBencerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBencerrarActionPerformed(evt);
            }
        });
        getContentPane().add(jBencerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, 150, 50));

        jBvoltarParaEleitor.setBackground(new java.awt.Color(0, 153, 153));
        jBvoltarParaEleitor.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBvoltarParaEleitor.setText("VOLTAR");
        jBvoltarParaEleitor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBvoltarParaEleitorActionPerformed(evt);
            }
        });
        getContentPane().add(jBvoltarParaEleitor, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 120, 40));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBencerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBencerrarActionPerformed
        if(jPFconfirmarFim.getText().equals("nimda")){
            dispose();
            Apuracao telaApuracao;
            telaApuracao = new Apuracao();
            telaApuracao.setVisible(true);
            
            
        }else{
            JOptionPane.showMessageDialog(null, "Senha não confere, por favor tente novamente!");
        }
    }//GEN-LAST:event_jBencerrarActionPerformed

    private void jBvoltarParaEleitorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBvoltarParaEleitorActionPerformed
            TelaAutEleitor telaEleitor;
            telaEleitor = new TelaAutEleitor();
            telaEleitor.setVisible(true);
    }//GEN-LAST:event_jBvoltarParaEleitorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConfirmarEncerramento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConfirmarEncerramento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConfirmarEncerramento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConfirmarEncerramento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConfirmarEncerramento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBencerrar;
    private javax.swing.JButton jBvoltarParaEleitor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField jPFconfirmarFim;
    // End of variables declaration//GEN-END:variables
}
