package Telas;

import DAO.EleitorDAO;
import Global.VariavelGlobal;
import classesModelo.Eleitor;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Luciana
 */
public class TelaAutEleitor extends javax.swing.JFrame {

    /**
     * Creates new form TelaAutEleitor
     */
    public TelaAutEleitor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTFentradaRg = new javax.swing.JTextField();
        jLfotoEleitor = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jBpesquisarEleitor = new javax.swing.JButton();
        jTFtituloEleitor = new javax.swing.JTextField();
        jBpesquisarEleitorTitulo = new javax.swing.JButton();
        jTFnomeEleitor = new javax.swing.JTextField();
        jTFdataNascEleitor = new javax.swing.JTextField();
        jTFzonaEleitor = new javax.swing.JTextField();
        jTFsecaoEleitor = new javax.swing.JTextField();
        jTFcidadeEleitor = new javax.swing.JTextField();
        jTFestadoEleitor = new javax.swing.JTextField();
        jBincluir = new javax.swing.JButton();
        jBnovaBusca = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jTFvotou = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jBvotar = new javax.swing.JButton();
        jBencerrarVotacao = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("IDENTIFICAÇÃO DO ELEITOR");
        setMinimumSize(new java.awt.Dimension(900, 540));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setText("RG:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jTFentradaRg.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(jTFentradaRg, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 330, 30));
        jPanel1.add(jLfotoEleitor, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 10, 100, 100));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setText("Data de Nasc.:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 130, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel4.setText("Nome:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel5.setText("Seção:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, -1, 20));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel6.setText("Título:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel7.setText("Estado:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 240, -1, 20));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel8.setText("Zona:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, 20));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel10.setText("Cidade:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, 20));

        jBpesquisarEleitor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBpesquisarEleitor.setText("BUSCAR");
        jBpesquisarEleitor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBpesquisarEleitorActionPerformed(evt);
            }
        });
        jPanel1.add(jBpesquisarEleitor, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, 120, 30));

        jTFtituloEleitor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(jTFtituloEleitor, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 330, 30));

        jBpesquisarEleitorTitulo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBpesquisarEleitorTitulo.setText("BUSCAR");
        jBpesquisarEleitorTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBpesquisarEleitorTituloActionPerformed(evt);
            }
        });
        jPanel1.add(jBpesquisarEleitorTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 60, 120, 30));

        jTFnomeEleitor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(jTFnomeEleitor, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 330, 30));

        jTFdataNascEleitor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(jTFdataNascEleitor, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 120, 130, 30));

        jTFzonaEleitor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(jTFzonaEleitor, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 160, 30));

        jTFsecaoEleitor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(jTFsecaoEleitor, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 170, 130, 30));

        jTFcidadeEleitor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(jTFcidadeEleitor, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 350, 30));

        jTFestadoEleitor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(jTFestadoEleitor, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 230, 150, 30));

        jBincluir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBincluir.setText("INCLUIR ELEITOR");
        jBincluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBincluirActionPerformed(evt);
            }
        });
        jPanel1.add(jBincluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 293, 170, 30));

        jBnovaBusca.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBnovaBusca.setText("NOVA BUSCA");
        jBnovaBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBnovaBuscaActionPerformed(evt);
            }
        });
        jPanel1.add(jBnovaBusca, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 150, 40));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel9.setText("Votou(S/N):");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 170, 100, 40));

        jTFvotou.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(jTFvotou, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 170, 70, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 760, 330));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("IDENTIFICAÇÃO DO ELEITOR");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, 390, 40));

        jBvotar.setBackground(new java.awt.Color(0, 153, 153));
        jBvotar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBvotar.setText("VOTAR");
        jBvotar.setEnabled(false);
        jBvotar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBvotarActionPerformed(evt);
            }
        });
        getContentPane().add(jBvotar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 430, 200, 50));

        jBencerrarVotacao.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBencerrarVotacao.setText("ENCERRAR VOTAÇÃO");
        jBencerrarVotacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBencerrarVotacaoActionPerformed(evt);
            }
        });
        getContentPane().add(jBencerrarVotacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 170, 30));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    
    
    private void jBvotarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBvotarActionPerformed
         
         dispose();
         Urna furna;
         furna = new Urna();
         furna.setVisible(true);
         
         
    }//GEN-LAST:event_jBvotarActionPerformed

    private void jBpesquisarEleitorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBpesquisarEleitorActionPerformed
        EleitorDAO dao;
        dao = new EleitorDAO();
        
        Eleitor ele;
        
        ele = dao.consultaEleitorPorRG(jTFentradaRg.getText());
        
        if(ele != null){
            
            VariavelGlobal.tituloEleitor = ele.getTitulo();
            
            jTFnomeEleitor.setText(ele.getNome());
            jTFtituloEleitor.setText(ele.getTitulo());
            jTFdataNascEleitor.setText(ele.getDataNasc());
            jTFzonaEleitor.setText(ele.getZona());
            jTFsecaoEleitor.setText(ele.getSecao());
            jTFcidadeEleitor.setText(ele.getCidade());
            jTFestadoEleitor.setText(ele.getEstado());
            jTFvotou.setText(ele.getVotou());
            
            jBincluir.setEnabled(false);
        }else{
            JOptionPane.showMessageDialog(null, "Eleitor não cadastrado!");
            jBincluir.setEnabled(true);
        }
        
        
    }//GEN-LAST:event_jBpesquisarEleitorActionPerformed

    private void jBpesquisarEleitorTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBpesquisarEleitorTituloActionPerformed
        EleitorDAO dao;
        dao = new EleitorDAO();
        
        Eleitor ele;
        
        ele = dao.consultaEleitorPorTitulo(jTFtituloEleitor.getText());
        
        if(ele != null){
            
//            ImageIcon fotoEleitores;
//            fotoEleitores = new ImageIcon(getClass().getResource("../imagensEleitores/" + ele.getFoto() ));

           
            
            VariavelGlobal.tituloEleitor = ele.getTitulo();
            
            jTFnomeEleitor.setText(ele.getNome());
            jTFentradaRg.setText(ele.getRg());
            jTFdataNascEleitor.setText(ele.getDataNasc());
            jTFzonaEleitor.setText(ele.getZona());
            jTFsecaoEleitor.setText(ele.getSecao());
            jTFcidadeEleitor.setText(ele.getCidade());
            jTFestadoEleitor.setText(ele.getEstado());
            jTFvotou.setText(ele.getVotou());
//            jLfotoEleitor.setIcon(fotoEleitores);
            
            jBincluir.setEnabled(false);
            
            if (ele.getVotou().equals("N") || ele.getVotou().equals("n")){
                jBvotar.setEnabled(true);
            }else{
                jBvotar.setEnabled(false);
            }
            
            
        }else{
            JOptionPane.showMessageDialog(null, "Eleitor não cadastrado!");
            jBincluir.setEnabled(true);
        }
        
    }//GEN-LAST:event_jBpesquisarEleitorTituloActionPerformed

    private void jBencerrarVotacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBencerrarVotacaoActionPerformed
        dispose();    
        ConfirmarEncerramento telaEncerrar;
            telaEncerrar = new ConfirmarEncerramento ();
            telaEncerrar.setVisible(true);
    }//GEN-LAST:event_jBencerrarVotacaoActionPerformed

    private void jBincluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBincluirActionPerformed
        Eleitor ele;
        ele = new Eleitor();
        
        
        ele.setRg(jTFentradaRg.getText());
        ele.setTitulo(jTFtituloEleitor.getText());
        ele.setNome(jTFnomeEleitor.getText());
        ele.setDataNasc(jTFdataNascEleitor.getText());
        ele.setZona(jTFzonaEleitor.getText());
        ele.setSecao(jTFsecaoEleitor.getText());
        ele.setCidade(jTFcidadeEleitor.getText());
        ele.setEstado(jTFestadoEleitor.getText());
        ele.setVotou(jTFvotou.getText());
         
        EleitorDAO bd;
        bd = new EleitorDAO();
        
        bd.adicionarEleitor(ele);
                 
        jTFentradaRg.setText("");
        jTFtituloEleitor.setText("");
        jTFnomeEleitor.setText("");
        jTFdataNascEleitor.setText("");
        jTFzonaEleitor.setText("");
        jTFsecaoEleitor.setText("");
        jTFcidadeEleitor.setText("");
        jTFestadoEleitor.setText("");
        jTFvotou.setText("");
          
    }//GEN-LAST:event_jBincluirActionPerformed

    private void jBnovaBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBnovaBuscaActionPerformed
        ImageIcon fotoLimpaEleitor;
        fotoLimpaEleitor = new ImageIcon("../imagensCandidatos/corrige.png");
        
        jTFentradaRg.setText("");
        jTFtituloEleitor.setText("");
        jTFnomeEleitor.setText("");
        jTFdataNascEleitor.setText("");
        jTFzonaEleitor.setText("");
        jTFsecaoEleitor.setText("");
        jTFcidadeEleitor.setText("");
        jTFestadoEleitor.setText("");
        jTFvotou.setText("");
        jLfotoEleitor.setIcon(fotoLimpaEleitor);
    }//GEN-LAST:event_jBnovaBuscaActionPerformed

    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAutEleitor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAutEleitor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAutEleitor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAutEleitor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAutEleitor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBencerrarVotacao;
    private javax.swing.JButton jBincluir;
    private javax.swing.JButton jBnovaBusca;
    private javax.swing.JButton jBpesquisarEleitor;
    private javax.swing.JButton jBpesquisarEleitorTitulo;
    private javax.swing.JButton jBvotar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLfotoEleitor;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTFcidadeEleitor;
    private javax.swing.JTextField jTFdataNascEleitor;
    private javax.swing.JTextField jTFentradaRg;
    private javax.swing.JTextField jTFestadoEleitor;
    private javax.swing.JTextField jTFnomeEleitor;
    private javax.swing.JTextField jTFsecaoEleitor;
    private javax.swing.JTextField jTFtituloEleitor;
    private javax.swing.JTextField jTFvotou;
    private javax.swing.JTextField jTFzonaEleitor;
    // End of variables declaration//GEN-END:variables
}
