package Telas;

import DAO.CandidatoDAO;
import DAO.EleitorDAO;
import Global.VariavelGlobal;
import classesModelo.Candidato;
import classesModelo.Eleitor;
import java.applet.Applet;
import java.applet.AudioClip;
import java.io.File;
import java.net.URL;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;

import javax.swing.JOptionPane;
import javax.swing.ImageIcon;




/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Luciana
 */
public class Urna extends javax.swing.JFrame {

    /**
     * Creates new form Urna
     */
    public Urna() {
        initComponents();
    }

    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jBnum1 = new javax.swing.JButton();
        jBnum3 = new javax.swing.JButton();
        jBnum4 = new javax.swing.JButton();
        jBnum9 = new javax.swing.JButton();
        jBnum6 = new javax.swing.JButton();
        jBnum7 = new javax.swing.JButton();
        jBnum8 = new javax.swing.JButton();
        jBnum5 = new javax.swing.JButton();
        jBnum0 = new javax.swing.JButton();
        jBnum2 = new javax.swing.JButton();
        jBconfirma = new javax.swing.JButton();
        jBbranco1 = new javax.swing.JButton();
        jBcorrige1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jTFnumero1 = new javax.swing.JTextField();
        jTFnumero2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLfotoCandidato = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLnomeCandidato = new javax.swing.JLabel();
        jLpartidoCandidato = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLvice = new javax.swing.JLabel();
        jLfotovice = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("URNA");
        setMinimumSize(new java.awt.Dimension(900, 501));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBnum1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jBnum1.setText("1");
        jBnum1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBnum1ActionPerformed(evt);
            }
        });
        jPanel1.add(jBnum1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 70, 47));

        jBnum3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jBnum3.setText("3");
        jBnum3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBnum3ActionPerformed(evt);
            }
        });
        jPanel1.add(jBnum3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, 70, 47));

        jBnum4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jBnum4.setText("4");
        jBnum4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBnum4ActionPerformed(evt);
            }
        });
        jPanel1.add(jBnum4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 70, 47));

        jBnum9.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jBnum9.setText("9");
        jBnum9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBnum9ActionPerformed(evt);
            }
        });
        jPanel1.add(jBnum9, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, 70, 47));

        jBnum6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jBnum6.setText("6");
        jBnum6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBnum6ActionPerformed(evt);
            }
        });
        jPanel1.add(jBnum6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 70, 47));

        jBnum7.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jBnum7.setText("7");
        jBnum7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBnum7ActionPerformed(evt);
            }
        });
        jPanel1.add(jBnum7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 70, 47));

        jBnum8.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jBnum8.setText("8");
        jBnum8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBnum8ActionPerformed(evt);
            }
        });
        jPanel1.add(jBnum8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 70, 47));

        jBnum5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jBnum5.setText("5");
        jBnum5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBnum5ActionPerformed(evt);
            }
        });
        jPanel1.add(jBnum5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 70, 47));

        jBnum0.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jBnum0.setText("0");
        jBnum0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBnum0ActionPerformed(evt);
            }
        });
        jPanel1.add(jBnum0, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 70, 47));

        jBnum2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jBnum2.setText("2");
        jBnum2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBnum2ActionPerformed(evt);
            }
        });
        jPanel1.add(jBnum2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 70, 47));

        jBconfirma.setBackground(new java.awt.Color(0, 102, 0));
        jBconfirma.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBconfirma.setText("CONFIRMA");
        jBconfirma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBconfirmaActionPerformed(evt);
            }
        });
        jPanel1.add(jBconfirma, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, 110, 60));

        jBbranco1.setBackground(new java.awt.Color(255, 255, 255));
        jBbranco1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBbranco1.setText("BRANCO");
        jBbranco1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBbranco1ActionPerformed(evt);
            }
        });
        jPanel1.add(jBbranco1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 90, 50));

        jBcorrige1.setBackground(new java.awt.Color(255, 51, 0));
        jBcorrige1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBcorrige1.setText("CORRIGE");
        jBcorrige1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBcorrige1ActionPerformed(evt);
            }
        });
        jPanel1.add(jBcorrige1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, 90, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 30, 330, 410));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTFnumero1.setEditable(false);
        jTFnumero1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jPanel2.add(jTFnumero1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 50, 60));

        jTFnumero2.setEditable(false);
        jTFnumero2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jPanel2.add(jTFnumero2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 50, 60));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("SEU VOTO PARA");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel2.setText("PRESIDENTE");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setText("Número:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel4.setText("Vice:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));
        jPanel2.add(jLfotoCandidato, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 120, 160));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel5.setText("Partido:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));

        jLnomeCandidato.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.add(jLnomeCandidato, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 340, 30));

        jLpartidoCandidato.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.add(jLpartidoCandidato, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 270, 30));

        jLabel6.setText("__________________________________________________________________________");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 470, 20));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel7.setText("Aperte a tecla:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("VERDE para CONFIRMAR ");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("LARANJA para CORRIGIR");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel10.setText("Nome:");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        jLvice.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel2.add(jLvice, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 200, 30));
        jPanel2.add(jLfotovice, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 40, 100, 110));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 510, 410));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

   
public void som(String nomeSom){ //tocar som de urna eletrônica
      URL url = getClass().getResource("/som/"+nomeSom);
      AudioClip audio = Applet.newAudioClip(url);
      audio.play();
  }
    
    
    private void setarNumero(String numero){
        int numCandidato = 0;
        if(jTFnumero1.getText().equals("")){
           jTFnumero1.setText(numero);
        }
        else{
            if(jTFnumero2.getText().equals("")){
            jTFnumero2.setText(numero);
            
                numCandidato = Integer.parseInt(jTFnumero1.getText() + jTFnumero2.getText());
              
                    
                    CandidatoDAO bd;
                    bd = new CandidatoDAO();
        
                    Candidato can;
                    can = new Candidato();
                    
        
                    can = bd.consultaCandidatoPorNumero(numCandidato);
        
                    if(can != null){
                    
                    ImageIcon fotoCandidato;
                    fotoCandidato = new ImageIcon(getClass().getResource("../imagensCandidatos/" + can.getFoto() ));
                    
                    ImageIcon fotoVice;
                    fotoVice = new ImageIcon(getClass().getResource("../imagensCandidatos/" + can.getFotovice() ));
                                       
                    jLnomeCandidato.setText( can.getNome() );
                    jLvice.setText( can.getVice() );
                    jLpartidoCandidato.setText( can.getPartido() );
                    jLfotoCandidato.setIcon(fotoCandidato);
                    jLfotovice.setIcon(fotoVice);
            
                    
                    }else{
                        jLnomeCandidato.setText("Nulo");
                        jLvice.setText("Nulo");
                        jLpartidoCandidato.setText("Nulo");
                        
                        
                    }
        }

    } 
}

    
    private void corrige(){
         
        ImageIcon fotoCandidatoCorrige;
        fotoCandidatoCorrige = new ImageIcon("../imagensCandidatos/corrige.png");
                    
        ImageIcon fotoViceCorrige;
        fotoViceCorrige = new ImageIcon("../imagensCandidatos/corrige.png");
        
        jTFnumero1.setText("");
        jTFnumero2.setText("");
        jLnomeCandidato.setText("");
        jLvice.setText(""); 
        jLpartidoCandidato.setText("");
        jLfotoCandidato.setIcon(fotoCandidatoCorrige);
        jLfotovice.setIcon(fotoViceCorrige);
             
        
    }
    

    
    
    private void jBnum1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBnum1ActionPerformed
        som("tecla.wav");    
        setarNumero("1");        
    }//GEN-LAST:event_jBnum1ActionPerformed

    private void jBnum2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBnum2ActionPerformed
        som("tecla.wav");    
        setarNumero("2"); 
    }//GEN-LAST:event_jBnum2ActionPerformed

    private void jBnum3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBnum3ActionPerformed
        som("tecla.wav");
        setarNumero("3");
    }//GEN-LAST:event_jBnum3ActionPerformed

    private void jBnum4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBnum4ActionPerformed
        som("tecla.wav");
        setarNumero("4");
    }//GEN-LAST:event_jBnum4ActionPerformed

    private void jBnum5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBnum5ActionPerformed
        som("tecla.wav");
        setarNumero("5");
    }//GEN-LAST:event_jBnum5ActionPerformed

    private void jBnum6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBnum6ActionPerformed
        som("tecla.wav");
        setarNumero("6");
    }//GEN-LAST:event_jBnum6ActionPerformed

    private void jBnum7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBnum7ActionPerformed
        som("tecla.wav");
        setarNumero("7");
    }//GEN-LAST:event_jBnum7ActionPerformed

    private void jBnum8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBnum8ActionPerformed
        som("tecla.wav");
        setarNumero("8");
    }//GEN-LAST:event_jBnum8ActionPerformed

    private void jBnum9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBnum9ActionPerformed
        som("tecla.wav");
        setarNumero("9");  
    }//GEN-LAST:event_jBnum9ActionPerformed

    private void jBnum0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBnum0ActionPerformed
        som("tecla.wav");
        setarNumero("0"); 
    }//GEN-LAST:event_jBnum0ActionPerformed

    private void jBconfirmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBconfirmaActionPerformed
          
           
      if (!jTFnumero1.getText().equals("") && !jTFnumero2.getText().equals("")){
          
        som("urna.wav");
        
        if(!"".equals(jTFnumero1.getText().trim()) && !"".equals(jTFnumero2.getText().trim())){
           
           int numCandidato = 0;
           if(jLnomeCandidato.getText().equals("Nulo")){
               numCandidato = 99;
            
                
           }else{
               numCandidato = Integer.parseInt(jTFnumero1.getText() + jTFnumero2.getText());
           }
           
        Candidato can;
        can = new Candidato();
        
        can.setNumero(numCandidato);
        
        CandidatoDAO bdc;
        bdc = new CandidatoDAO();
        
        
        bdc.computarVoto(can);
           
        }
        
        
        Eleitor ele;
        ele = new Eleitor();
        
        ele.setTitulo(VariavelGlobal.tituloEleitor);
         
        EleitorDAO bde;
        bde = new EleitorDAO();
        
        
        bde.computarVotoEleitor(ele);
        
         corrige();
         
         
                 
         TelaAutEleitor feleitor;
         feleitor = new TelaAutEleitor();
         feleitor.setVisible(true);
         
         dispose();
                
        
      }
    }//GEN-LAST:event_jBconfirmaActionPerformed

    private void jBcorrige1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBcorrige1ActionPerformed
        som("tecla.wav");
        corrige();
    }//GEN-LAST:event_jBcorrige1ActionPerformed

    private void jBbranco1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBbranco1ActionPerformed
    som("tecla.wav");
    setarNumero("0");
    setarNumero("0");
    
    int numCandidato = 0;
    numCandidato = Integer.parseInt(jTFnumero1.getText() + jTFnumero2.getText());
       
    CandidatoDAO bd;
    bd = new CandidatoDAO();
        
    Candidato can;
    can = new Candidato();
        
    can = bd.consultaCandidatoPorNumero(numCandidato);
        
        if(can != null){
            
            ImageIcon fotoCandidato;
            fotoCandidato = new ImageIcon(getClass().getResource("../imagensCandidatos/branco.png" + can.getFoto() ));
                    
            ImageIcon fotoVice;
            fotoVice = new ImageIcon(getClass().getResource("../imagensCandidatos/branco.png" + can.getFotovice() ));
                                       
            jLnomeCandidato.setText( can.getNome() );
            jLvice.setText( can.getVice() );
            
            jLfotoCandidato.setIcon(fotoCandidato);
            jLfotovice.setIcon(fotoVice);
            
            }else{
                jLnomeCandidato.setText("Nulo");
                jLvice.setText("Nulo");
                jLpartidoCandidato.setText("Nulo");
                }
        
        
        
        
    }//GEN-LAST:event_jBbranco1ActionPerformed
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Urna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Urna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Urna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Urna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Urna().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBbranco1;
    private javax.swing.JButton jBconfirma;
    private javax.swing.JButton jBcorrige1;
    private javax.swing.JButton jBnum0;
    private javax.swing.JButton jBnum1;
    private javax.swing.JButton jBnum2;
    private javax.swing.JButton jBnum3;
    private javax.swing.JButton jBnum4;
    private javax.swing.JButton jBnum5;
    private javax.swing.JButton jBnum6;
    private javax.swing.JButton jBnum7;
    private javax.swing.JButton jBnum8;
    private javax.swing.JButton jBnum9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLfotoCandidato;
    private javax.swing.JLabel jLfotovice;
    private javax.swing.JLabel jLnomeCandidato;
    private javax.swing.JLabel jLpartidoCandidato;
    private javax.swing.JLabel jLvice;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTFnumero1;
    private javax.swing.JTextField jTFnumero2;
    // End of variables declaration//GEN-END:variables
}
